### PR TITLE
Create translation_cs.xml

### PR DESCRIPTION
**Pull request by mowenxuan**
China regional language file-Chinese

### CODE REVIEW

**Comment by ZhooL** [comment]
Thank you :-)

**Comment by mowenxuan** [comment]
Request to open a pull request, I want to change some punctuation and spaces in the translation

**Comment by mowenxuan** [comment]
I changed some of the punctuation and indentation in the translation.
[translation_cs.zip](https://github.com/user-attachments/files/17966508/translation_cs.zip)

**Comment by ZhooL** [comment]
Will make it in the next release. Have seen the file here too late

**Comment by mowenxuan** [comment]
Update translation and optimize Chinese layout
[translation_cs.zip](https://github.com/user-attachments/files/17972894/translation_cs.zip)

**Pull request merged**
